#create the functions in the cluster
---
  - hosts: master-host
    become: true

  - name: Read in list of functions to create
    hosts: localhost
    vars:
      input: "{{ lookup('file','{{playbook_dir}}/../functions.json') | from_json }}"

    tasks:
      - name: Create function list
        set_fact: 
          functions: "{{ input.functions }}"
      
      - name: Play to loop over functions and create all
        include_tasks: includes/eventing-tasks.yml
        loop: "{{functions}}"
